kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pricelist-db-pvc
  namespace: pricelist
  labels:
    pricelist-storage: "yes"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  storageClassName: ""
  volumeName: pricelist-db-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pricelist-storage: "yes"
