---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-examples
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/christianh814/gitops-examples.git

