---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops-examples
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./bgd-k8s/overlays/kind
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-examples

